//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnnn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.MonDaChons = new HashSet<MonDaChon>();
        }
    
        public string MaNV { get; set; }
        public string HoVaTenNV { get; set; }
        public string Tuoi { get; set; }
        public string DiaChiNV { get; set; }
        public string SDT { get; set; }
        public string GioiTinh { get; set; }
        public string LoaiNV { get; set; }
        public string LuongCB { get; set; }
        public string CaLV { get; set; }
        public byte[] HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonDaChon> MonDaChons { get; set; }
    }
}
