//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnnn
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Quyen { get; set; }
        public string TenNguoiDung { get; set; }
        public string GioiTinh { get; set; }
    }
}
